# Generated by Django 5.2.7 on 2026-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.CharField(max_length=50, verbose_name='Expéditeur')),
                ('contenu', models.TextField(verbose_name='Contenu du message')),
                ('date_reception_telephone', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception (téléphone)')),
                ('date_reception_serveur', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception (serveur)')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP source')),
            ],
            options={
                'verbose_name': 'Message SMS',
                'verbose_name_plural': 'Messages SMS',
                'ordering': ['-date_reception_serveur'],
            },
        ),
    ]
